name: Checks
on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        types: [opened, synchronize]
env:
    NODE_OPTIONS: "--max_old_space_size=4096"
    SKIP_ENV_VALIDATION: true
    GRPC_API_BASE_URL: "http://localhost:3001"
    AUTH0_BASE_URL: "http://localhost:3000"
jobs:
    lint-and-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install devbox
              uses: jetify-com/devbox-install-action@v0.11.0
              with:
                  enable-cache: "true"
            - name: Install dependencies
              run: devbox run -- pnpm install
            - name: Lint
              run: devbox run -- pnpm lint
            - name: Build
              run: devbox run -- pnpm build
